name: myo
version: 0.1.1.0
synopsis: neovim layout & command manager
description: Please see the README on GitHub at <https://github.com/tek/myo-hs>
github: "tek/myo-hs"
license: MIT
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2018 Torsten Schmits"
category: Neovim
build-type: Simple

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- ribosome >= 0.1.2
- chiasma
- cornea
- nvim-hs
- unliftio
- unliftio-core
- data-default
- lens
- hslogger
- deepseq
- messagepack
- prettyprinter
- containers
- parsec
- parsers
- conduit
- conduit-extra
- stm-conduit
- stm-chans
- resourcet
- bytestring
- typed-process
- filepath
- directory
- split
- messagepack
- transformers
- strings
- uuid
- mtl
- free
- unix
- network
- text
- exceptions
- either
- attoparsec
- transformers-base
- monad-control
- lifted-base
- stringsearch
- composition-extra
- utf8-string

library:
 source-dirs: lib

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UnicodeSyntax
- ViewPatterns

executables:
 myo:
  main: Main.hs
  source-dirs: app
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - myo

tests:
  myo-unit:
    main: SpecMain.hs
    source-dirs: test/u
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - myo
    - ribosome-test
    - HTF
